spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl_auto: create
        show_sql: true
    open-in-view: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .html

datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:test # In-Memory mode
  username: sa
  password:

sql:
  init:
    mode: always
    schema-locations: classpath:schema.sql
    data-locations: classpath:data.sql
#logging:
#  level:
#    org.springframework: DEBUG
#    org.hibernate: DEBUG
#    org.springframework.jdbc.core: TRACE